# Generated by Django 4.2.9 on 2025-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medication_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('child', 'Child'), ('guardian', 'Guardian'), ('friend', 'Friend'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
